spring.datasource.url=jdbc:postgresql://db:5432/taskdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=taskuser
spring.datasource.password=taskpass

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

spring.kafka.enabled=false